// Fixed fictional model/configuration examples. Prices are not rental offers or FX quotes.
export type CarFixture = {
  id: string;
  name: string;
  kind: string;
  energy: string;
  price: number;
  seats: number;
  bags: number;
  line: string;
  note: string;
  deposit: number;
  xiaomi?: boolean;
  aliases?: string[];
};
export const CAR_CATALOG: readonly CarFixture[] = [
  {
    id: "su7",
    name: "Xiaomi SU7",
    kind: "Sport sedan",
    energy: "Electric",
    price: 78,
    seats: 5,
    bags: 3,
    line: "A different kind of city escape.",
    note: "A sleek electric concept for the longer way home.",
    deposit: 500,
    xiaomi: true,
  },
  {
    id: "yu7",
    name: "Xiaomi YU7",
    kind: "Electric SUV",
    energy: "Electric",
    price: 92,
    seats: 5,
    bags: 4,
    line: "Room for the spontaneous detour.",
    note: "The SUV concept for a little more space and a lot of curiosity.",
    deposit: 550,
    xiaomi: true,
  },
  {
    id: "ultra",
    name: "Xiaomi SU7 Ultra",
    kind: "Performance sedan",
    energy: "Electric",
    price: 168,
    seats: 5,
    bags: 2,
    line: "Make the drive part of the trip.",
    note: "A performance-led showcase, included purely for this concept.",
    deposit: 900,
    xiaomi: true,
  },
  {
    id: "civic",
    name: "Honda Civic Sport Touring Hybrid",
    kind: "Hybrid sedan",
    energy: "Hybrid",
    price: 62,
    seats: 5,
    bags: 3,
    line: "A little sport. A lot of possibility.",
    note: "A sport-minded hybrid concept for city exploring and the scenic route.",
    deposit: 350,
    aliases: ["honda civic", "civic sport", "civic hybrid"],
  },
  {
    id: "countryman",
    name: "MINI Countryman",
    kind: "Electric SUV",
    energy: "Electric",
    price: 76,
    seats: 5,
    bags: 3,
    line: "Go big on the little adventures.",
    note: "The all-electric Countryman SE is our roomy MINI reference for this preview.",
    deposit: 400,
    aliases: ["countryman"],
  },
  {
    id: "crown",
    name: "Toyota Crown Signia",
    kind: "Hybrid crossover",
    energy: "Hybrid",
    price: 88,
    seats: 5,
    bags: 4,
    line: "Settle in. Seek out somewhere new.",
    note: "A refined hybrid crossover concept for a more unhurried escape.",
    deposit: 500,
    aliases: ["crown signia", "crown insignia", "crowninsignia"],
  },
  {
    id: "model3",
    name: "Tesla Model 3",
    kind: "Electric sedan",
    energy: "Electric",
    price: 68,
    seats: 5,
    bags: 3,
    line: "Less fuss. More open road.",
    note: "A clean, quiet electric option for your sample itinerary.",
    deposit: 400,
  },
  {
    id: "i4",
    name: "BMW i4",
    kind: "Gran coupé",
    energy: "Electric",
    price: 96,
    seats: 5,
    bags: 3,
    line: "A rewarding change of scenery.",
    note: "A grand-touring example for the scenic route.",
    deposit: 600,
  },
  {
    id: "taycan",
    name: "Porsche Taycan",
    kind: "Performance sedan",
    energy: "Electric",
    price: 154,
    seats: 4,
    bags: 2,
    line: "The journey gets a starring role.",
    note: "An electric sports-car idea for a memorable long weekend.",
    deposit: 850,
  },
  {
    id: "ex30",
    name: "Volvo EX30",
    kind: "Compact SUV",
    energy: "Electric",
    price: 64,
    seats: 5,
    bags: 2,
    line: "Small footprint. Big weekend.",
    note: "A compact electric idea for city streets and coastal stops.",
    deposit: 350,
  },
  {
    id: "mini",
    name: "MINI Cooper SE",
    kind: "City car",
    energy: "Electric",
    price: 49,
    seats: 4,
    bags: 1,
    line: "A small car with weekend energy.",
    note: "A compact city-car example. Check luggage fit before choosing.",
    deposit: 300,
  },
  {
    id: "yaris",
    name: "Toyota Yaris",
    kind: "City car",
    energy: "Hybrid",
    price: 36,
    seats: 5,
    bags: 2,
    line: "Keep it simple. Go explore.",
    note: "A budget-minded example for a lighter trip.",
    deposit: 250,
  },
  {
    id: "golf",
    name: "Volkswagen Golf",
    kind: "Hatchback",
    energy: "Petrol",
    price: 42,
    seats: 5,
    bags: 2,
    line: "The easygoing all-rounder.",
    note: "A familiar hatchback concept for everyday flexibility.",
    deposit: 300,
  },
  {
    id: "ioniq",
    name: "Hyundai IONIQ 5",
    kind: "Electric crossover",
    energy: "Electric",
    price: 74,
    seats: 5,
    bags: 3,
    line: "Space to take the longer route.",
    note: "An electric crossover example with a relaxed road-trip feel.",
    deposit: 450,
  },
  {
    id: "eqe",
    name: "Mercedes-Benz EQE",
    kind: "Executive sedan",
    energy: "Electric",
    price: 114,
    seats: 5,
    bags: 3,
    line: "A calmer way to arrive.",
    note: "An executive electric concept for a quieter journey.",
    deposit: 650,
  },
];
